version: "4"
services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped